<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <Compile Remove="Views\NewFolder\**" />
    <EmbeddedResource Remove="Views\NewFolder\**" />
    <None Remove="Views\NewFolder\**" />
    <Page Remove="Views\NewFolder\**" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Shared\RaktarAppShared\RaktarAppShared.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.0" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

</Project>
